apiVersion: v1
kind: ConfigMap
metadata:
  name: flash-sale-config
  namespace: flash-sale
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "flash_sale"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
