apiVersion: v1
kind: Secret
metadata:
  name: flash-sale-secrets
  namespace: flash-sale
type: Opaque
stringData:
  DATABASE_URL: "postgresql://admin:password123@postgres-service:5432/flash_sale"
  REDIS_URL: "redis://redis-service:6379/0"
  SECRET_KEY: "change-this-to-a-random-secret-key-in-production-flask-sale-2025"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_HOURS: "24"
